networks:
  server_network:
    name: server_network
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 81:8080
    networks:
      - server_network
    depends_on:
      - my_server
  my_server:
    container_name: server
    build: .
    ports:
      - 80:81
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server_network